[versions]
## Android gradle plugin
androidGradlePlugin = "8.13.0"
android-compileSdk = "35"
android-minSdk = "28"
android-targetSdk = "35"
ktlint = "12.1.1"

# https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md
androidDesugarJdkLibs = "2.1.5"

## AndroidX
# https://developer.android.com/jetpack/androidx/releases/core
androidxCore = "1.15.0"
# https://developer.android.com/jetpack/androidx/releases/appcompat
androidxAppCompat = "1.7.0"
# https://developer.android.com/jetpack/androidx/releases/lifecycle
androidxLifecycle = "2.8.7"
# https://developer.android.com/jetpack/androidx/releases/activity
androidxActivity = "1.10.1"
# https://developer.android.com/jetpack/androidx/releases/datastore
androidxDatastore = "1.1.3"
# https://developer.android.com/jetpack/androidx/releases/glance
androidxGlance = "1.1.1"
glanceExperimentalTools = "0.2.2"
# https://developer.android.com/jetpack/androidx/releases/profileinstaller
profileinstaller = "1.4.1"
# https://androidx.tech/artifacts/benchmark/benchmark-baseline-profile-gradle-plugin/index.html
baselineprofile = "1.3.3"

## Compose
# Jetbrains Compose
composePlugin = "1.7.3"
#composePlugin = "1.4.0"
# Compose Navigations for Compose multiplatform
composeNavigation = "2.8.0-alpha10"
# https://developer.android.com/develop/ui/compose/bom/bom-mapping
androidxComposeBom = "2025.02.00"
# https://developer.android.com/jetpack/androidx/releases/navigation
androidxComposeNavigation = "2.8.8"
# https://developer.android.com/jetpack/androidx/releases/compose-material3
androidxComposeMaterial3 = "1.3.1"
uiBackhandler = "1.8.0-alpha03"

# https://github.com/skydoves/landscapist
landscapist = "2.4.6"
# https://github.com/valentinilk/compose-shimmer
composeShimmer = "1.3.2"
# compose-hot-reload https://github.com/JetBrains/compose-hot-reload
compose-hot-reload = "1.0.0-dev.34.1"

## Kotlin Symbol Processing
# https://github.com/google/ksp/
ksp = "2.2.20-2.0.2"
#ksp = "1.9.10-1.0.13"

## Hilt
# https://github.com/google/dagger/releases
hilt = "2.55"
# https://developer.android.com/jetpack/androidx/releases/hilt
hiltNavigationCompose = "1.2.0"

## Koin
# koin https://github.com/InsertKoinIO/koin
koin = "4.0.2"
# koin annotations https://github.com/InsertKoinIO/koin-annotations/releases
koin-annotations = "2.0.0"

## Network
# https://github.com/Foso/Ktorfit
ktorfit = "2.6.4"
# https://github.com/ktorio/ktor
ktor = "3.2.1"

## File
okio = "3.10.2"

## Kotlin
# https://github.com/JetBrains/kotlin
kotlin = "2.2.20"
#kotlin = "1.9.10"
# https://github.com/Kotlin/kotlinx.serialization
kotlinxSerializationJson = "1.8.0"
# https://github.com/Kotlin/kotlinx-datetime/releases
kotlinxDatetime = "0.6.2"
# https://github.com/Kotlin/kotlinx.collections.immutable
kotlinxImmutable = "0.3.8"

## Coroutine
# https://github.com/cashapp/turbine
turbine = "1.2.0"
# https://github.com/Kotlin/kotlinx.coroutines
coroutine = "1.10.1"

## license
# https://developers.google.com/android/guides/opensource
ossLicenses = "17.1.0"
ossLicensesPlugin = "0.10.6"

## Test
# https://github.com/junit-team/junit4
junit4 = "4.13.2"
# https://mvnrepository.com/artifact/org.junit.vintage/junit-vintage-engine
junitVintageEngine = "5.12.0"
ui-test-junit4 = "1.7.8"
# https://developer.android.com/jetpack/androidx/releases/test-uiautomator
uiAutomator = "2.3.0"
androidxTestRunner = "1.6.2"
# https://developer.android.com/jetpack/androidx/releases/benchmark
benchmarkMacroJunit4 = "1.3.3"

# # https://developer.android.com/jetpack/androidx/releases/test
androidxTestExt = "1.2.1"
androidxEspresso = "3.6.1"
# # https://github.com/takahirom/roborazzi
roborazzi = "1.40.1"
# https://github.com/robolectric/robolectric/releases
robolectric = "4.14.1"
# https://kotest.io/
kotest = "5.9.0"
# https://github.com/detekt/detekt
detekt = "1.23.7"
# https://mockk.io/
mockk = "1.13.16"

## Logging
# kermit https://github.com/touchlab/Kermit
kermit = "2.0.5"

buildKonfig = "0.17.1"

# image
ui-graphics = "1.9.0-rc01"
skiko = "0.9.22"
kamel-image = "1.0.0-beta.4"
coil = "3.3.0"
image-loader = "1.10.0"

datastore = "1.1.1"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastore" }
androidx-datastore-core-okio = { group = "androidx.datastore", name = "datastore-core-okio", version.ref = "androidxDatastore" }
androidx-datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "androidxDatastore" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiAutomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "ui-test-junit4" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxComposeNavigation" }
androidx-compose-navigation-test = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxComposeNavigation" }
compose-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-gradle-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composePlugin" }
compose-ui-backhandler = { group = "org.jetbrains.compose.ui", name = "ui-backhandler", version.ref = "uiBackhandler" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

ktorfit-lib = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-serialization-json-okio = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-okio", version.ref = "kotlinxSerializationJson" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }

landscapist-bom = { group = "com.github.skydoves", name = "landscapist-bom", version.ref = "landscapist" }
landscapist-coil = { group = "com.github.skydoves", name = "landscapist-coil" }
landscapist-coil3 = { group = "com.github.skydoves", name = "landscapist-coil3", version.ref = "landscapist" }
landscapist-placeholder = { group = "com.github.skydoves", name = "landscapist-placeholder", version.ref = "landscapist" }
landscapist-animation = { group = "com.github.skydoves", name = "landscapist-animation" }

compose-shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "composeShimmer" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junitVintageEngine" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazziRule = { module = "io.github.takahirom.roborazzi:roborazzi-junit-rule", version.ref = "roborazzi" }
roborazziCompose = { module = "io.github.takahirom.roborazzi:roborazzi-compose", version.ref = "roborazzi" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
inject = "javax.inject:javax.inject:1"
kotest-runner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutine" }

oss-licenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "ossLicenses" }

# verify
verify-detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }

# kermit
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

# plugin
verify-detektPlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
oss-licenses-plugin = { group = "com.google.android.gms", name = "oss-licenses-plugin", version.ref = "ossLicensesPlugin" }

androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "androidxGlance" }
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "androidxGlance" }
glance-tools-appwidget-host = { group = "com.google.android.glance.tools", name = "appwidget-host", version.ref = "glanceExperimentalTools" }

# kotest
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

#image
ui-graphics = { module = "org.jetbrains.compose.ui:ui-graphics", version.ref = "ui-graphics" }
skiko = { module = "org.jetbrains.skiko:skiko", version.ref = "skiko" }
kamel-image = { module = "com.alialbaali.kamel:kamel-image", version.ref = "kamel-image" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
image-loader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "image-loader" }

# datastore
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }


[bundles]
ktor = [
    "ktor-client-core",
    "ktor-logging",
    "ktor-client-encoding",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json",
    "ktor-client-auth"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
verify-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "composePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
roborazzi-plugin = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
compose-hotreload = { id = "org.jetbrains.compose-hot-reload", version.ref = "compose-hot-reload" }
kotest-multiplatform = { id = "io.kotest.multiplatform", version.ref = "kotest" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }