server:
  http_listen_port: ${PROMTAIL_PORT}

# 로그 위치 설정
positions:
  filename: /tmp/positions.yaml

# Loki 서버 설정
clients:
  - url: ${LOKI_URL}

# Spring Boot 로그 디렉토리의 모든 .log 파일을 스크랩하도록 설정
scrape_configs:
  - job_name: main-server
    static_configs:
      - targets:
        - localhost
        labels:
          job: main-server
          __path__: /var/log/spring-boot/*.log