services:
  loki:
    image: grafana/loki
    restart: always
    container_name: "talktobook-loki"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - loki_data:/var/loki
    networks:
      - talktobook-monitoring-network

  grafana:
    image: grafana/grafana
    restart: always
    container_name: "talktobook-grafana"
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - loki
    networks:
      - talktobook-monitoring-network

volumes:
  loki_data:
  grafana_data:

networks:
  talktobook-monitoring-network:
    driver: bridge
